# Generated by Django 2.2.8 on 2019-12-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=36)),
                ('name', models.TextField()),
                ('image', models.ImageField(unique=True, upload_to='images/')),
                ('approval', models.BooleanField(default=True)),
            ],
        ),
    ]
